baseURL = 'https://ferwanguer.github.io/blog'
languageCode = 'en-us'
title = 'Fernando Wangüemert Guerra'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A non-political political Blog"
# Google analytics code
googleAnalytics = "G-P7F1V0MGD9"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Como vamos, bienvenido.'
homeIntroContent = """
Welcome to this online space, where I occasionally post what I write about my musings and the topics that interest me.
I've divided them into science, politics, existential critique, and finally, fictional tales in which I hope you don't see yourself reflected. 
Most of the content will be written in Spanish, language of civilized people. Nevertheless, I hope you enjoy what you read. Tons of fun foreseen, you'll
be relieved to know that everything published here came from the lingering fingers of a human.

Cheers,

Fer

*04 Septiembre 2024*
"""

# Collection to display on home
homeCollectionTitle = 'You can start with'
homeCollection = 'stories'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = false

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/fernando-wanguemert-guerra-200522145/"

[[params.social]]
name = "X"
url = "https://x.com/demarquezortega"

[[params.social]]
name = "github"
url = "https://github.com/ferwanguer"

# Main menu pages
[[params.menu]]
name = "Home"
url = "/blog"

[[params.menu]]
name = "Stories"
url = "/blog/stories"

[[params.menu]]
name = "Politics"
url = "/blog/politics"

[[params.menu]]
name = "Critique"
url = "/blog/general-critique"

[[params.menu]]
name = "About"
url = "/blog/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'bw'

# Giscus comments
[params.giscus]
enable = true
repo = "ferwanguer/blog"
repoid = "R_kgDOMsqAbA"
category = "General"
categoryid = "DIC_kwDOMsqAbM4CiM0e"
mapping = "pathname"
theme = "preferred_color_scheme"